# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i2dMi1bdMtqBcTH12Ogdje6UOpa-no0a
"""

# ============================================================
# DAY 3 — KNOWLEDGE BASE + HYBRID RAG (FINAL)
# ============================================================

!pip install -q PyPDF2 rank_bm25 numpy sentence-transformers chromadb

import os
import json
import numpy as np
import PyPDF2
import chromadb
from google.colab import files
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer
from datetime import datetime

print("=" * 70)
print("📚 DAY 3 — KNOWLEDGE BASE + HYBRID SEARCH (FINAL)")
print("=" * 70)

# ============================================================
# 1. UPLOAD PDF FILES
# ============================================================

print("\n📁 Upload ALL Knowledge Base PDF files (10 files):")
print("   1. Khait_Plant_Sounds_2023.pdf")
print("   2. FAO_Crop_Water_Response_66.pdf")
print("   3. FAO_Irrigation_Manual.pdf")
print("   4. MEWA_Tomato_Irrigation_Guide.pdf")
print("   5. AIAdoptionFramework.pdf")
print("   6. ai-principles.pdf")
print("   7. Personal_Data_Protection_Law.pdf")
print("   8. Saudi_GAP.pdf")
print("   9. SaudiWaterResourcesCode.pdf")
print("   10. الاستراتيجية_الوطنية_للمياه_2030.pdf")

uploaded = files.upload()

pdf_files = [f for f in uploaded.keys() if f.lower().endswith(".pdf")]

print(f"\n✅ Number of PDF files uploaded: {len(pdf_files)}")

if len(pdf_files) < 10:
    print(f"⚠️ Warning: Expected 10 files, but only {len(pdf_files)} were uploaded.")

for i, f in enumerate(pdf_files, 1):
    print(f"   {i}. {f}")

if len(pdf_files) == 0:
    raise ValueError("❌ No PDF files were uploaded.")

# ============================================================
# 2. EXTRACT TEXT PAGE BY PAGE
# ============================================================

def extract_pdf_pages(pdf_path):
    pages = []
    try:
        with open(pdf_path, "rb") as file:
            reader = PyPDF2.PdfReader(file)
            print(f"\n📄 {pdf_path} → {len(reader.pages)} pages")
            for page_number, page in enumerate(reader.pages, start=1):
                text = page.extract_text()
                if text and text.strip():
                    pages.append({
                        "source": pdf_path,
                        "page": page_number,
                        "text": text.strip()
                    })
    except Exception as e:
        print(f"⚠️ Error reading {pdf_path}: {e}")
    return pages

all_pages = []
print("\n" + "=" * 70)
print("📖 EXTRACTING TEXT")
print("=" * 70)

for pdf in pdf_files:
    pages = extract_pdf_pages(pdf)
    all_pages.extend(pages)

print(f"\n✅ Total pages with extracted text: {len(all_pages)}")

# ============================================================
# 3. CREATE CHUNKS
# ============================================================

def create_chunks(pages, chunk_size=700, overlap=100):
    chunks = []
    chunk_id = 0
    for page_data in pages:
        text = page_data["text"]
        start = 0
        while start < len(text):
            end = start + chunk_size
            chunk_text = text[start:end].strip()
            if len(chunk_text) > 100:
                chunks.append({
                    "id": f"chunk_{chunk_id}",
                    "text": chunk_text,
                    "source": page_data["source"],
                    "page": page_data["page"]
                })
                chunk_id += 1
            start += chunk_size - overlap
    return chunks

print("\n" + "=" * 70)
print("✂️ CREATING CHUNKS")
print("=" * 70)

chunks = create_chunks(all_pages, chunk_size=700, overlap=100)
print(f"✅ Number of chunks: {len(chunks)}")

# ============================================================
# 4. BM25 KEYWORD SEARCH
# ============================================================

print("\n" + "=" * 70)
print("🔎 BUILDING BM25 KEYWORD SEARCH")
print("=" * 70)

chunk_texts = [c["text"] for c in chunks]
tokenized_chunks = [t.lower().split() for t in chunk_texts]
bm25 = BM25Okapi(tokenized_chunks)
print("✅ BM25 ready.")

# ============================================================
# 5. LOAD EMBEDDING MODEL
# ============================================================

print("\n" + "=" * 70)
print("🧠 LOADING EMBEDDING MODEL")
print("=" * 70)

embedding_model = SentenceTransformer(
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)
print("✅ Embedding model loaded.")

# ============================================================
# 6. CREATE EMBEDDINGS
# ============================================================

print("\n" + "=" * 70)
print("🔢 CREATING EMBEDDINGS")
print("=" * 70)

embeddings = embedding_model.encode(
    chunk_texts,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)
print(f"✅ Embeddings shape: {embeddings.shape}")

# ============================================================
# 7. CREATE CHROMADB VECTOR DATABASE
# ============================================================

print("\n" + "=" * 70)
print("🗄️ CREATING VECTOR DATABASE")
print("=" * 70)

client = chromadb.PersistentClient(path="./chroma_knowledge_base")
try:
    client.delete_collection("agri_knowledge_base")
except:
    pass

collection = client.create_collection("agri_knowledge_base")

collection.add(
    ids=[c["id"] for c in chunks],
    documents=chunk_texts,
    embeddings=[e.tolist() for e in embeddings],
    metadatas=[{"source": c["source"], "page": str(c["page"])} for c in chunks]
)

print(f"✅ ChromaDB ready. Chunks stored: {collection.count()}")

# ============================================================
# 8. SEARCH FUNCTIONS
# ============================================================

def bm25_search(query, top_k=5):
    scores = bm25.get_scores(query.lower().split())
    top = np.argsort(scores)[::-1][:top_k]
    results = []
    for r, idx in enumerate(top, 1):
        if scores[idx] > 0:
            results.append({
                "rank": r,
                "text": chunks[idx]["text"],
                "source": chunks[idx]["source"],
                "page": chunks[idx]["page"],
                "score": float(scores[idx])
            })
    return results

def vector_search(query, top_k=5):
    q_emb = embedding_model.encode([query], normalize_embeddings=True)[0]
    res = collection.query(
        query_embeddings=[q_emb.tolist()],
        n_results=top_k,
        include=["documents", "metadatas", "distances"]
    )
    results = []
    for i in range(len(res["documents"][0])):
        results.append({
            "rank": i + 1,
            "text": res["documents"][0][i],
            "source": res["metadatas"][0][i]["source"],
            "page": res["metadatas"][0][i]["page"],
            "distance": res["distances"][0][i]
        })
    return results

def hybrid_search(query, top_k=5, candidate_k=10):
    bm25_res = bm25_search(query, top_k=candidate_k)
    vec_res = vector_search(query, top_k=candidate_k)

    rrf_scores = {}
    result_data = {}
    k = 60

    for r in bm25_res:
        cid = f"{r['source']}_{r['page']}"
        rrf_scores[cid] = rrf_scores.get(cid, 0) + 1 / (k + r["rank"])
        result_data[cid] = {"text": r["text"], "source": r["source"], "page": r["page"]}

    for r in vec_res:
        cid = f"{r['source']}_{r['page']}"
        rrf_scores[cid] = rrf_scores.get(cid, 0) + 1 / (k + r["rank"])
        if cid not in result_data:
            result_data[cid] = {"text": r["text"], "source": r["source"], "page": r["page"]}

    ranked = sorted(rrf_scores, key=rrf_scores.get, reverse=True)[:top_k]
    results = []
    for rank, cid in enumerate(ranked, 1):
        results.append({
            "rank": rank,
            "hybrid_score": rrf_scores[cid],
            "text": result_data[cid]["text"],
            "source": result_data[cid]["source"],
            "page": result_data[cid]["page"]
        })
    return results

# ============================================================
# 9. RUN AND SAVE RESULTS
# ============================================================

print("\n" + "=" * 70)
print("🧪 RUNNING HYBRID SEARCH TESTS")
print("=" * 70)

test_queries = [
    "What irrigation practices are recommended for tomato plants?",
    "What are the signs of drought stress in plants?",
    "How can water resources be managed efficiently in agriculture?",
    "What agricultural practices support sustainable water use?",
    "ما هي ممارسات الري الموصى بها لنباتات الطماطم؟",
    "ما هي علامات الإجهاد المائي في النباتات؟"
]

all_results = []

for query in test_queries:
    print(f"\n🔍 Query: {query}")
    results = hybrid_search(query, top_k=3, candidate_k=10)
    all_results.append({"query": query, "results": results})
    for r in results:
        print(f"   Rank {r['rank']} → {r['source'][:40]}... (score: {r['hybrid_score']:.3f})")

# ============================================================
# 10. SAVE OUTPUTS
# ============================================================

print("\n" + "=" * 70)
print("💾 SAVING OUTPUTS")
print("=" * 70)

# Save metadata
metadata = {
    "timestamp": datetime.now().isoformat(),
    "pdf_files": pdf_files,
    "total_pdfs": len(pdf_files),
    "total_pages": len(all_pages),
    "total_chunks": len(chunks),
    "embedding_model": "paraphrase-multilingual-MiniLM-L12-v2",
    "vector_db": "ChromaDB",
    "keyword_search": "BM25",
    "hybrid_method": "RRF"
}

with open("knowledge_base_metadata.json", "w", encoding="utf-8") as f:
    json.dump(metadata, f, ensure_ascii=False, indent=4)

print("✅ metadata.json saved")

# Save hybrid search results
with open("Day3_Hybrid_Search_Results.txt", "w", encoding="utf-8") as f:
    f.write("=" * 70 + "\n")
    f.write("DAY 3 — HYBRID SEARCH RESULTS\n")
    f.write(f"Generated: {datetime.now().isoformat()}\n")
    f.write("=" * 70 + "\n\n")

    for entry in all_results:
        f.write(f"🔍 QUERY: {entry['query']}\n")
        f.write("-" * 50 + "\n")
        for r in entry["results"]:
            f.write(f"🏆 Rank {r['rank']}\n")
            f.write(f"📄 Source: {r['source']}\n")
            f.write(f"📑 Page: {r['page']}\n")
            f.write(f"⭐ Score: {r['hybrid_score']:.4f}\n")
            f.write(f"📋 Text: {r['text'][:500]}...\n\n")
        f.write("=" * 70 + "\n\n")

print("✅ Day3_Hybrid_Search_Results.txt saved")

# ============================================================
# 11. SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("🎉 DAY 3 COMPLETED SUCCESSFULLY")
print("=" * 70)
print("""
✅ 10 PDF files processed
✅ Page-level extraction
✅ Chunking (700 chars, 100 overlap)
✅ BM25 keyword search
✅ Multilingual embeddings
✅ ChromaDB vector database
✅ Hybrid search (RRF)
✅ Results saved
✅ Metadata saved

📁 FILES GENERATED:
   - chroma_knowledge_base/   ← IMPORTANT for Day 4
   - knowledge_base_metadata.json
   - Day3_Hybrid_Search_Results.txt

📌 Keep these files for Day 4!
""")
print("=" * 70)

import shutil
shutil.make_archive("chroma_knowledge_base", 'zip', "chroma_knowledge_base")
print("✅ تم ضغط المجلد بنجاح!")

